sudo: required
language: c
os:
  - linux
compiler: 
  - gcc -coverage -O0 main.c -o main ./main gcov main.c
addons:
  apt:
    packages:
    - cmake
    - check

script: make ./ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
