sudo: required
language: c
os:
  - linux

before_install:
  - sudo apt-get install -y check 
  - sudo apt-get install -y lcov

before script:
  - cmake .

script:
  - make
  - make test
  - lcov --directory . --capture --output-file coverage.info

after_success:
  - bash <(curl -s https://codecov.io/bash)
