sudo: required
language: c
os:
  - linux
compiler: 
  - gcc
addons:
  apt:
    packages:
    - cmake
    - check

script: /configure && make && make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
