sudo: required
language: c
os:
  - linux
compiler: 
  - gcc

script:
  - gcc main.c ./src/*.c -I./include -lcheck
  - echo program compiled successfully
after_success:
  - bash <(curl -s https://codecov.io/bash)
