sudo: required
language: c
os:
  - linux
compiler: 
  - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y check
  - sudo apt-get install -y codecov

script:
  - make
  - echo program compiled successfully
after_success:
  - bash <(curl -s https://codecov.io/bash)
