sudo: required
language: c
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y check
  - sudo pip install codecov

script:
  - make
  - echo program compiled successfully
after_success:
  - bash <(curl -s https://codecov.io/bash)
